version: 0.2

phases:
    install:
        commands:
            - echo Installing Node 12...
            - curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
            - bash nodesource_setup.sh
            - apt install -y nodejs
            - node -v
    pre_build:
        commands:
            - echo Installing dependencies...
            - npm i
    build:
        commands:
            - echo tres..
            - npm run build

artifacts:
    files:
        - "**/*"
    base-directory: "build"
